scrumapp_core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from scrumapp.views import ProjectDetail, ProjectList, ProjectUpdate, SprintCreate, SprintDetail, SprintUpdate, StoryCreate, StoryDetail, StoryList, StoryUpdate

urlpatterns = [
    path('projects', ProjectList.as_view(), name='project_list'),
    path('projects/<int:project_id>', ProjectDetail.as_view(), name='project_detail'),
    path('projects/<int:project_id>/edit', ProjectUpdate.as_view(), name='project_edit'),

    path('projects/<int:project_id>/sprints/<int:pk>', SprintDetail.as_view(), name='sprint_detail'),
    path('projects/<int:project_id>/sprints/create', SprintCreate.as_view(), name='sprint_create'),
    path('projects/<int:project_id>/sprints/<int:pk>/edit', SprintUpdate.as_view(), name='sprint_edit'),

    path('projects/<int:project_id>/stories', StoryList.as_view(), name='story_list'),
    path('projects/<int:project_id>/stories/<int:pk>', StoryDetail.as_view(), name='story_detail'),
    path('projects/<int:project_id>/stories/create', StoryCreate.as_view(), name='story_create'),
    path('projects/<int:project_id>/stories/<int:pk>/edit', StoryUpdate.as_view(), name='story_edit'),

    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('project_list'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Duplicate URL names are allowed by Django, but we don't want them in this project, so make sure they don't happen
names = [pattern.name for pattern in urlpatterns if getattr(pattern, "name", None)]
assert len(names) == len(set(names)), f"Duplicate URL names: {names}"

scrumapp/models.py
from functools import cached_property

from django.contrib.auth.models import User
from django.db import models
from django.forms import ValidationError
from django.urls import reverse_lazy
from django.utils import timezone

from scrumapp.validators import date_not_in_past


class RoleEnum(models.TextChoices):
    DEVELOPER = "DEV", "Developer"
    SCRUM_MASTER = "SM", "Scrum Master"
    PRODUCT_OWNER = "PO", "Product Owner"

class ProjectMember(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=RoleEnum.choices)

class Project(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name
    
    # These use .all() to take advantage of query caching, but we still need to confirm queries are actually cached
    
    @cached_property
    def product_owner(self) -> User:
        for pm in self.projectmember_set.all():
            if pm.role == RoleEnum.PRODUCT_OWNER:
                return pm.user
            
    @cached_property
    def scrum_master(self) -> User:
        for pm in self.projectmember_set.all():
            if pm.role == RoleEnum.SCRUM_MASTER:
                return pm.user
    
    @cached_property
    def developers(self) -> list[User]:
        return [pm.user for pm in self.projectmember_set.all() if pm.role == RoleEnum.DEVELOPER]
    
    def get_absolute_url(self):
        return reverse_lazy("project_detail", kwargs={"project_id": self.id})
    

# A custom manager for Sprint so we can DRY our queries
class SprintQuerySet(models.QuerySet):
    def active(self):
        now = timezone.now()
        return self.filter(start_date__lte=now, end_date__gte=now)


class Sprint(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField(default=False)
    velocity = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Velocity (pts)")

    objects = SprintQuerySet.as_manager()

    def __str__(self):
        return self.name

    def clean(self):
        if self.start_date > self.end_date:
            raise ValidationError({
                "start_date": "Start date cannot be after end date"
            })
        # Only run this validation on new objects (when creating)
        if self.id is None:
            if self.start_date < timezone.now().date():
                raise ValidationError({
                    "start_date": "Start date cannot be in the past"
                })

        # TODO: turn this into a field validation
        if self.velocity == 0:
            raise ValidationError({
                "velocity": "Velocity cannot be 0"
            })

        if self.velocity > (self.end_date - self.start_date).days * 6:
            raise ValidationError({
                "velocity": "Max points in sprint duration is: " + str((self.end_date - self.start_date).days * 6)
            })
        
    def get_absolute_url(self):
        return reverse_lazy("sprint_detail", kwargs={"project_id": self.project.id, "pk": self.id})


class Story(models.Model):
    class Priority(models.IntegerChoices):
        MUST_HAVE = 1, 'Must have'
        SHOULD_HAVE = 2, 'Should have'
        COULD_HAVE = 3, 'Could have'
        WONT_HAVE = 4, "Won't have at this time"

    class Status(models.IntegerChoices):
        UNASSIGNED = 1, "Unassigned"
        ASSIGNED = 2, "Assigned"
        ACTIVE = 3, "Active"
        FINISHED = 4, "Finished"

    sprint = models.ForeignKey(Sprint, null=True, blank=True, on_delete=models.SET_NULL)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    assigned_to = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True, blank=True)
    priority = models.IntegerField(choices=Priority)
    status = models.IntegerField(choices=Status, default=1)
    value = models.FloatField()
    time_estimate = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("story_detail", kwargs={"project_id": self.project.id, "pk": self.id})

    class Meta:
        verbose_name_plural = "stories"


class Task(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    assigned_to = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True, blank=True)
    hours = models.IntegerField()

    def __str__(self):
        return self.title

scrumapp/views.py
from typing import Any
from django import forms
from django.db.models import Q
from django.utils import timezone
from django.views.generic import FormView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from scrumapp.formfields import HTML5DateInput

from scrumapp.models import Project, RoleEnum, Sprint, Story, ProjectMember


class ProjectMemberMixin(LoginRequiredMixin, PermissionRequiredMixin):
    allowed_roles = ()

    project = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        return context

    def has_permission(self) -> bool:
        if not self.request.user.is_authenticated:
            return False
        
        # (DON'T PLACE ANYTHING ABOVE THIS!)
        # For order-of-execution reasons, we get the project here and save it to the view instance
        project_id = self.kwargs['project_id']
        if project_id is None:
            raise Exception("project_id not found in the URL - did you forget to include it in the URL pattern?")
        self.project = Project.objects.get(id=project_id)

        # Superuser can do anything
        if self.request.user.is_superuser:
            return True

        # Check that the user has one of the allowed roles
        if self.allowed_roles:
            for pm in self.project.projectmember_set.all():
                if pm.user_id == self.request.user.id and pm.role in self.allowed_roles:
                    return True
            return False

        return True


class ProjectList(LoginRequiredMixin, ListView):
    model = Project
    context_object_name = "projects"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        # We're already getting the project list from the context preprocessor
        return {}


class ProjectDetail(LoginRequiredMixin, DetailView):
    model = Project
    context_object_name = "project"
    pk_url_kwarg = "project_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["stories"] = Story.objects.filter(project=self.object, sprint=None)
        
        context['active'] = Sprint.objects.filter(project=self.object).active()
        context['future'] = Sprint.objects.filter(project=self.object, start_date__gt=timezone.now())
        context['past'] = Sprint.objects.filter(project=self.object, end_date__lt=timezone.now())
        return context


# class ProjectMemberForm(forms.ModelForm):
#     class Meta:
#         model = ProjectMember
#         fields = ('user', 'role',)


# class ProjectMembersView(ProjectMemberMixin, FormView):
#     template_name = "scrumapp/projectmembers_form.html"
#     def get_form(self, form_class: type | None = ...) -> forms.BaseForm:
#         form = forms.modelformset_factory(ProjectMember, form=ProjectMemberForm, extra=0)
#         return form


class ProjectUpdate(ProjectMemberMixin, UpdateView):
    model = Project
    context_object_name = "project"
    template_name_suffix = "_form"
    pk_url_kwarg = "project_id"
    allowed_roles = (RoleEnum.SCRUM_MASTER)
    
    def get_form(self):
        form = super().get_form()
        form.fields['developers'].initial = User.objects.filter(projectmember__project=self.project, projectmember__role=RoleEnum.DEVELOPER)
        return form

    class form_class(forms.ModelForm):
        developers = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)

        class Meta:
            model = Project
            fields = ('name', 'description', 'developers')

        def save(self, commit: bool = ...) -> Any:
            # TODO: transaction
            project = super().save(commit=False)

            users = set(self.cleaned_data['developers'])

            # Very clean set stuff courtesy of Math Man™
            all = set(User.objects.filter(projectmember__project=project, projectmember__role=RoleEnum.DEVELOPER))
            to_add = users - all
            to_remove = all - users
            
            for user in to_add:
                ProjectMember.objects.create(project=project, user=user, role=RoleEnum.DEVELOPER)
            
            ProjectMember.objects.filter(project=project, user__in=to_remove).delete()
            
            return super().save(commit)

class SprintDetail(ProjectMemberMixin, DetailView):
    model = Sprint
    context_object_name = "sprint"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['unassigned'] = Story.objects.filter(project=self.project, sprint=self.object,
            status=Story.Status.UNASSIGNED)
        ctx['assigned'] = Story.objects.filter(project=self.project, sprint=self.object,
            status=Story.Status.ASSIGNED)
        ctx['active'] = Story.objects.filter(project=self.project, sprint=self.object,
            status=Story.Status.ACTIVE)
        ctx['finished'] = Story.objects.filter(project=self.project, sprint=self.object,
            status=Story.Status.FINISHED)
        return ctx


class SprintFormView(ProjectMemberMixin, FormView):
    model = Sprint
    allowed_roles = (RoleEnum.SCRUM_MASTER)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        return ctx

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        if end_date <= start_date:
            raise forms.ValidationError("End date should be after start date.")
        has_overlap = Sprint.objects.filter(Q(project=self.project),
            Q(end_date__gte=start_date) | Q(start_date__lte=end_date)).exists()
        if has_overlap:
            raise forms.ValidationError('Start and end date overlap with another sprint')
        return cleaned_data

    def form_valid(self, form):
        form.instance.project = self.project
        return super().form_valid(form)
    
    def get_initial(self):
        return {'start_date': timezone.now(), 'end_date': timezone.now() + timezone.timedelta(days=7), 'velocity': 1}

    # We're overriding the form class to make the date fields use the HTML5 date input type. Normally we could just omit this and Django would use the default form class.
    class form_class(forms.ModelForm):
        class Meta:
            model = Sprint
            fields = ('name', 'description', 'start_date', 'end_date', 'velocity')

            widgets = {
                'start_date': HTML5DateInput(),
                'end_date': HTML5DateInput(),
            }

class SprintCreate(SprintFormView, CreateView):
    template_name_suffix = '_form'


class SprintUpdate(SprintFormView, UpdateView):
    template_name_suffix = '_form'


class StoryList(ProjectMemberMixin, ListView):
    model = Story
    context_object_name = "story"


class StoryDetail(ProjectMemberMixin, DetailView):
    model = Story
    context_object_name = "story"


class StoryFormView(ProjectMemberMixin, FormView):
    model = Story
    fields = ('sprint', 'title', 'description', 'assigned_to', 'priority', 'value', 'time_estimate')
    allowed_roles = (RoleEnum.SCRUM_MASTER, RoleEnum.PRODUCT_OWNER)

    def get_form(self):
        form = super().get_form()
        form.fields['sprint'].queryset = Sprint.objects.filter(project=self.project)
        return form

    def clean(self):
        cleaned_data = super().clean()
        same_title_exists = Story.objects.filter(project=self.project,
            title__iexact=self.object.title).exists()
        if same_title_exists:
            raise forms.ValidationError('There is another story with the same title')
        return cleaned_data

    def form_valid(self, form):
        form.instance.project = self.project
        return super().form_valid(form)


class StoryCreate(StoryFormView, CreateView):
    template_name_suffix = '_form'


class StoryUpdate(StoryFormView, UpdateView):
    template_name_suffix = '_form'

scrumapp/templates/scrumapp/base.html
{% load scrumapp %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<title>
		{% block title %}

		{% endblock %}
	</title>

	<style>
		body {
			min-height: 100vh;
		}
	</style>

	{% block head %}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
		crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
		integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
		crossorigin="anonymous" referrerpolicy="no-referrer" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js"
		integrity="sha512-GWzVrcGlo0TxTRvz9ttioyYJ+Wwk9Ck0G81D+eO63BaqHaJ3YZX9wuqjwgfcV/MrB2PhaVX9DkYVhbFpStnqpQ=="
		crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	{% endblock %}
</head>

<body class="d-flex flex-nowrap">
	<nav class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 15em;">
		<!-- HEADER -->
		<a href="/" class="nav-link border-bottom py-2">
			<h3>Scrumapp</h3>
		</a>

		<!-- MAIN NAV-->
		<div class="container my-3">
			{% for listed_project in projects %}
			<div class="row">
				<a href="{% url 'project_detail' project_id=listed_project.id %}"
					class="btn btn-outline-light my-2 {%if listed_project.id == project.id %}active {%endif%}">
					{{listed_project.name}}
				</a>
			</div>
			{% endfor %}
		</div>

		<!-- USER DROPDOWN -->
		{% if request.user.is_authenticated %}
		<div class="dropdown mt-auto border-top pt-3">
			<a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
				data-bs-toggle="dropdown" aria-expanded="false">
				<img src="https://github.com/{{ user.username }}.png" alt="" width="32" height="32"
					class="rounded-circle me-2">
				<strong>{{ user.username }}</strong>
			</a>
			<ul class="dropdown-menu dropdown-menu-dark text-small shadow">
				<li>
					<a class="dropdown-item" href="#">Profile</a>
				</li>
				<li>
					<hr class="dropdown-divider">
				</li>
				{% if request.user.is_superuser %}
				<li>
					<a href="/admin" class="dropdown-item text-info">
						Admin panel
					</a>
				</li>
				{% endif %}
				<li>
					<hr class="dropdown-divider">
				</li>
				<li>
					<form method="post" action="{% url 'logout' %}">
						{% csrf_token %}
						<button class="dropdown-item text-danger" type="submit">Log Out</button>
					</form>
				</li>
			</ul>
		</div>
		{% endif %}
	</nav>
	<main class="container-fluid p-4">
		{% block main %}

		{% endblock %}
	</main>
</body>

</html>

scrumapp/templates/scrumapp/project_detail.html
{% extends "scrumapp/base.html" %}
{% block main %}

<section>
    <div class="row">
        <a href="{% url 'project_list' %}" class="col-1 btn btn-outline-dark btn-sm py-1 my-2">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
        <h2 class="col font-weight-bold text-center">{{ project.name }}</h2>
    </div>
    <p>{{ project.description }}</p>
    <p>
        <strong><i class="fa-solid fa-user-ninja"></i> Scrum master:</strong> {{ project.scrum_master }} <br>
        <strong><i class="fa-solid fa-user-tie"></i> Product owner:</strong> {{project.product_owner }} <br>
        <strong><i class="fa-solid fa-users"></i> Developers:</strong> {% for member in project.developers %}{{member}}{% if not forloop.last %}, {% endif %}{% endfor %}
    </p>

    <a href="{% url 'project_edit' project_id=project.id %}" class="btn btn-warning btn-sm">Edit</a>
    {% if request.user.is_superuser %}
    <a target="_blank" href="/admin/scrumapp/project/{{project.id}}/change/" class="btn btn-danger btn-sm">Admin</a>
    {% endif %}
</section>

<section class="p-3 my-2">
    <a href="{% url 'sprint_create' project.id %}?next={{request.url}}" class="btn btn-success btn-sm my-2 float-end">
        <i class="fa fa-plus"></i> Sprint</a>
    </div>
    <h4 class="text-center py-2">Sprints</h4>
    <nav>
        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-active-tab" data-bs-toggle="tab" data-bs-target="#nav-active"
                type="button" role="tab" aria-controls="nav-active" aria-selected="true">Active</button>
            <button class="nav-link" id="nav-future-tab" data-bs-toggle="tab" data-bs-target="#nav-future" type="button"
                role="tab" aria-controls="nav-future" aria-selected="false">Future</button>
            <button class="nav-link" id="nav-past-tab" data-bs-toggle="tab" data-bs-target="#nav-past" type="button"
                role="tab" aria-controls="nav-past" aria-selected="false">Past</button>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-active" role="tabpanel" aria-labelledby="nav-active-tab">
            {% include "scrumapp/partial/sprint_list.html" with sprints=active %}
        </div>
        <div class="tab-pane fade" id="nav-future" role="tabpanel" aria-labelledby="nav-future-tab">
            {% include "scrumapp/partial/sprint_list.html" with sprints=future %}
        </div>
        <div class="tab-pane fade" id="nav-past" role="tabpanel" aria-labelledby="nav-past-tab">
            {% include "scrumapp/partial/sprint_list.html" with sprints=past %}
        </div>
    </div>

    <header class="d-flex justify-content-between mt-4">
        <h2>Backlog of stories</h2>
        <div>
            <a href="{% url 'story_list' project.id %}" class="me-2">See all stories in the backlog</a>
            <a href="{% url 'story_create' project.id %}?next={{request.url}}" class="btn btn-primary">Create story</a>
        </div>
    </header>
    <main>
        {% include "scrumapp/partial/story_list.html" with stories=stories %}
    </main>
</section>

{% endblock %}

scrumapp/templates/scrumapp/project_form.html
{% extends "scrumapp/base.html" %}
{% load crispy_forms_filters %}

{% block head %}
{{ block.super }}
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"
/>
<script src="https://cdn.jsdelivr.net/npm/choices.js@9.0.1/public/assets/scripts/choices.min.js"></script>
{% endblock %}

{% block main %}

<h2>Edit project</h2>

<form method="POST" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-5">Save</button>
</form>

<script>
    new Choices('#id_developers', {
        removeItemButton: true,
    });
</script>
{% endblock %}

scrumapp/templates/scrumapp/project_list.html
{% extends "scrumapp/base.html" %}
{% block main %}
<header class="d-flex justify-content-between">
    <h2 class="text-center font-weight-bold py-3">Projects</h2>
    <div>
        {% if request.user.is_superuser %}
        <a href="/admin/scrumapp/project/add" class="btn btn-primary btn-sm">Create project</a>
        {% endif %}
    </div>
</header>

<section>
    {% for project in projects %}
    <div class="card mx-5 my-2">
        <div class="card-body">
            <a href="{{ project.get_absolute_url }}" class="card-block text-decoration-none text-reset">
                <h5 class="card-title">
                    {{project.name }}
                </h5>
                <p class="card-text">{{ project.description }}</p>
                <p>
                    <small>
                        <strong><i class="fa-solid fa-user-ninja"></i> Scrum master:</strong> {{ project.scrum_master }} <br>
                        <strong><i class="fa-solid fa-user-tie"></i> Product owner:</strong> {{project.product_owner }} <br>
                        <strong><i class="fa-solid fa-users"></i> Developers:</strong> {% for member in project.developers %}{{member}}{% endfor %}
                    </small>
                </p>

                <div class="d-flex justify-content-between">
                    <div>
                        <a href="{% url 'project_edit' project_id=project.id %}" class="btn btn-warning btn-sm">Edit</a>
                        {% if request.user.is_superuser %}
                        <a target="_blank" href="/admin/scrumapp/project/{{project.id}}/change/" class="btn btn-danger btn-sm">Admin</a>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% empty %}
    You have no projects
    {% endfor %}
</section>
{% endblock %}

scrumapp/templates/scrumapp/sprint_detail.html
{% extends "scrumapp/base.html" %}
{% block main %}

<section>    
    <div class="row">
        <a href="{{ project.get_absolute_url }}"  class="col-1 btn btn-outline-dark btn-sm py-1 my-2">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
        <h2 class="col font-weight-bold text-center">{{ sprint.name }}</h2>
    </div>
    <p>
        <strong>Date: </strong> {{ sprint.start_date }} -> {{ sprint.end_date }}
    </p>
    <p>
        <strong>Velocity:</strong> {{ sprint.velocity|default_if_none:"?" }}
    </p>
    <p class="my-2 py-1">{{ sprint.description }}</p>

    {% if request.user.is_superuser %}
    <a target="_blank" href="/admin/scrumapp/sprint/{{sprint.id}}/change/" class="btn btn-danger btn-sm">Admin</a>
    {% endif %}
    <a href="{% url 'sprint_edit' project_id=sprint.project.id pk=sprint.id %}" class="btn btn-warning btn-sm">Edit</a>  
</section>

<section class="mt-4">
    <h3>Unassigned</h3>
    <main>
        {% include 'scrumapp/partial/story_list.html' with stories=unassigned %}
    </main>

    <h3>Assigned</h3>
    <main>
        {% include 'scrumapp/partial/story_list.html' with stories=assigned %}
    </main>

    <h3>Active</h3>
    <main>
        {% include 'scrumapp/partial/story_list.html' with stories=active %}
    </main>

    <h3>Finished</h3>
    <main>
        {% include 'scrumapp/partial/story_list.html' with stories=assigned %}
    </main>
</section>

{% endblock %}

scrumapp/templates/scrumapp/sprint_form.html
{% extends "scrumapp/base.html" %}
{% load crispy_forms_filters %}
{% block main %}

<h2>{{form.is_bound|yesno:"Edit,Create"}} sprint</h2>

<form method="POST" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="{{ project.get_absolute_url }}"  class="btn btn-danger">Cancel</a>
</form>

{% endblock %}

scrumapp/templates/scrumapp/story_detail.html
{% extends "scrumapp/base.html" %}
{% block main %}

<section>
    <h2>{{ story.title }}</h2>
    <p><b>Sprint:</b> {{ story.sprint.name }}</p>
    <p><b>Assigned to:</b> {{ story.assigned_to.username }}</p>
    <p><b>Priority:</b> {{ story.get_priority_display }}</p>
    <p><b>Status:</b> {{ story.get_status_display }}</p>
    <p><b>Business value:</b> {{ story.value }} pts</p>
    <p><b>Estimated time:</b> {{ story.time_estimate }} pts</p>
    <p><b>Description:</b> {{ story.description }}</p>

    {% if request.user.is_superuser %}<a target="_blank" href="/admin/scrumapp/story/{{story.id}}/change/" class="btn btn-danger btn-sm">Admin</a>{% endif %}
    <a href="{% url 'story_edit' project_id=story.project.id pk=story.id %}" class="btn btn-warning btn-sm">Edit</a>
</section>

{% endblock %}

scrumapp/templates/scrumapp/story_form.html
{% extends "scrumapp/base.html" %}
{% load crispy_forms_filters %}
{% block main %}

<h2>{{form.is_bound|yesno:"Edit,Create"}} story</h2>

<form method="POST" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>

{% endblock %}